apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-express-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-express-example
  template:
    metadata:
      labels:
        app: kubernetes-express-example
    spec:
      containers:
      - name: kubernetes-express-example
        image: kubernetes-express-example:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-express-example-service
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-express-example
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
