apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-express-example-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-express-example
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
